/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week10;

import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class NewJFrame extends javax.swing.JFrame {
    private long hitungKarakter = 0;
    private long hitungBaris = 0;
    private long hitungVokal = 0;
    private long hitungKonsonan = 0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        contentTextArea = new javax.swing.JTextArea();
        prosesButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        saveProsesTextButton = new javax.swing.JButton();
        jumlahKarakterLabel = new javax.swing.JLabel();
        jumlahBarisLabel = new javax.swing.JLabel();
        jumlahKarakterTextField = new javax.swing.JTextField();
        jumlahBarisTextField = new javax.swing.JTextField();
        jumlahVokalLabel = new javax.swing.JLabel();
        jumlahKonsonanLabel = new javax.swing.JLabel();
        jumlahVokalTextField = new javax.swing.JTextField();
        jumlahKonsonanTextField = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contentTextArea.setColumns(20);
        contentTextArea.setRows(5);
        contentTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contentTextAreaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(contentTextArea);

        prosesButton.setText("Proses Text");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear Text Area");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        saveProsesTextButton.setText("Save Proses Text (*.txt)");
        saveProsesTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProsesTextButtonActionPerformed(evt);
            }
        });

        jumlahKarakterLabel.setText("Jumlah Karakter Di luar Spasi :");

        jumlahBarisLabel.setText("Jumlah Baris :");

        jumlahVokalLabel.setText("Jumlah Huruf Vokal :");

        jumlahKonsonanLabel.setText("Jumlah Huruf Konsonan :");

        jMenu1.setText("File");

        openMenuItem.setText("Open (*.txt)");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openMenuItem);

        saveMenuItem.setText("Save (*.txt)");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(saveMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prosesButton)
                        .addGap(18, 18, 18)
                        .addComponent(clearButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jumlahBarisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jumlahBarisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jumlahKarakterLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jumlahKarakterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveProsesTextButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jumlahKonsonanLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jumlahKonsonanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jumlahVokalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jumlahVokalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prosesButton)
                    .addComponent(clearButton)
                    .addComponent(saveProsesTextButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlahKarakterLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jumlahKarakterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jumlahVokalLabel)
                        .addComponent(jumlahVokalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahBarisLabel)
                    .addComponent(jumlahBarisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahKonsonanLabel)
                    .addComponent(jumlahKonsonanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitungChar (String content){
        hitungKarakter = content.chars()
                .filter(c -> c != ' ' && c != '\n')
                .count();
        
        hitungBaris = contentTextArea.getLineCount();
        
        hitungVokal = content.chars()
                .mapToObj(ch -> (char) ch)
                .filter(ch -> "AIUEOaiueo".contains(ch.toString()))
                .count();
        
        hitungKonsonan = content.chars()
                .mapToObj(ch -> (char) ch)
                .filter(ch -> Character.isLetter(ch) && 
                        !"AEIOUaeiou".contains(ch.toString()))
                .count();
    }
    
    private void tampilkanPenghitungan(){
        jumlahKarakterTextField.setText(Long.toString(hitungKarakter));
        jumlahBarisTextField.setText(Long.toString(hitungBaris));
        jumlahVokalTextField.setText(Long.toString(hitungVokal));
        jumlahKonsonanTextField.setText(Long.toString(hitungKonsonan));
    }
 
        private void simpanPenghitungan(){
        ActionEvent event = new ActionEvent(this, ActionEvent.ACTION_PERFORMED, "");
        prosesButtonActionPerformed(event);
        
        String filePath = "output.txt";
        
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
            // Write content to the file
            writer.write("Hasil Proses Teks");
            writer.newLine();
            
            writer.write("=================");
            writer.newLine();
            
            
            writer.write("Jumlah Karakter (diluar Spasi): " + Long.toString(hitungKarakter));
            writer.newLine();
            
            writer.write("Jumlah Baris: " + Long.toString(hitungBaris));
            writer.newLine();
            
            writer.write("Jumlah Huruf Vokal: " + Long.toString(hitungVokal));
            writer.newLine();
            
            writer.write("Jumlah Huruf Konsonan: " + Long.toString(hitungKonsonan));
            writer.newLine();

            writer.flush();
            
            JOptionPane.showMessageDialog(this, "Berhasil disimpan!");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
        
    private void bukaFile(){
        JFileChooser choose = new JFileChooser();
        int returnValue = choose.showOpenDialog(null);

        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectFile = choose.getSelectedFile();
            if (selectFile != null) {
                String fileName = selectFile.getName();
                String extension = fileName.substring(fileName.lastIndexOf(".") + 1);
                if (!extension.equalsIgnoreCase("txt")) {
                    // The selected file is a .txt file
                    JOptionPane.showMessageDialog(null, "Format file salah!", "Warning",
                            JOptionPane.WARNING_MESSAGE);
                } else {
                    // The selected file is not a .txt file
                    try {
                        FileReader reader = new FileReader(selectFile);
                        BufferedReader br = new BufferedReader(reader, 16384);

                        String str = "";
                        String strRead = "";
                        while ((strRead = br.readLine()) != null) {
                            str = str + strRead + '\n';
                        }
                        str = str.substring(0, str.length()-1);
                        contentTextArea.setText(str);
                        br.close();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Terjadi Error!.", "Warning",
                                JOptionPane.WARNING_MESSAGE);
                    }

                }
            }
        }
    }
    
    
        
    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:
        simpanPenghitungan();
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
        // TODO add your handling code here:
        String content = contentTextArea.getText();
        
        hitungChar(content);
        tampilkanPenghitungan();
    }//GEN-LAST:event_prosesButtonActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        bukaFile();
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        contentTextArea.setText("");
        jumlahKarakterTextField.setText("");
        jumlahBarisTextField.setText("");
        jumlahVokalTextField.setText("");
        jumlahKonsonanTextField.setText("");    
    }//GEN-LAST:event_clearButtonActionPerformed

    private void saveProsesTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProsesTextButtonActionPerformed
        // TODO add your handling code here:
        simpanPenghitungan();
    }//GEN-LAST:event_saveProsesTextButtonActionPerformed

    private void contentTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contentTextAreaMouseClicked
        // TODO add your handling code here:
        contentTextArea.setFocusable(true);
    }//GEN-LAST:event_contentTextAreaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JTextArea contentTextArea;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jumlahBarisLabel;
    private javax.swing.JTextField jumlahBarisTextField;
    private javax.swing.JLabel jumlahKarakterLabel;
    private javax.swing.JTextField jumlahKarakterTextField;
    private javax.swing.JLabel jumlahKonsonanLabel;
    private javax.swing.JTextField jumlahKonsonanTextField;
    private javax.swing.JLabel jumlahVokalLabel;
    private javax.swing.JTextField jumlahVokalTextField;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JButton prosesButton;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton saveProsesTextButton;
    // End of variables declaration//GEN-END:variables
}
